version: "3.1"
services:
  db:
    image: mysql:8.0.17
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql_data:/var/lib/mysql
      - ./db/mysql_init:/docker-entrypoint-initdb.d
      - ./db/mysql_conf/:/etc/mysql/conf.d
    environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: test
            MYSQL_PASSWORD: test